-- DROP TABLE item cascade;
-- DROP TABLE users cascade;
-- DROP TABLE bookings cascade;
-- DROP TABLE comment cascade;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(50) NOT NULL,
    is_available BOOLEAN,
    owner_id BIGINT,
    CONSTRAINT fk_item_owner_id FOREIGN KEY(owner_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR(50),

    CONSTRAINT fk_bookings_item_id FOREIGN KEY(item_id) REFERENCES item (id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_user_id FOREIGN KEY(booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(500) NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_comment_item_id FOREIGN KEY(item_id) REFERENCES item (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_user_id FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
